//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcGISRestToolkit.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArcGISRestToolkit.Resource.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao consultar o serviço de Geração de Token..
        /// </summary>
        internal static string msgAGOTokenManager_Error {
            get {
                return ResourceManager.GetString("msgAGOTokenManager_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro retornado pelo serviço de Geração de Token: - Código: {0} - Mensagem: {1} - Detalhes: {2}.
        /// </summary>
        internal static string msgAGOTokenManager_Result_Error {
            get {
                return ResourceManager.GetString("msgAGOTokenManager_Result_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A &quot;where clause&quot; não pode estar em branco..
        /// </summary>
        internal static string msgFeatureServiceConnector_Error_BlankWhereClause {
            get {
                return ResourceManager.GetString("msgFeatureServiceConnector_Error_BlankWhereClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não pode haver um item nulo na coleção..
        /// </summary>
        internal static string msgFeatureServiceConnector_Error_NullFeatureInTheList {
            get {
                return ResourceManager.GetString("msgFeatureServiceConnector_Error_NullFeatureInTheList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não pode haver um item nulo na coleção..
        /// </summary>
        internal static string msgFeatureServiceConnector_Error_NullItemInOutFieldsList {
            get {
                return ResourceManager.GetString("msgFeatureServiceConnector_Error_NullItemInOutFieldsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro durante a consulta dos das features no ArcGIS Online..
        /// </summary>
        internal static string msgFeatureServiceConnector_Error_Query {
            get {
                return ResourceManager.GetString("msgFeatureServiceConnector_Error_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao consultar o serviço - Código: {0} - Mensagem: {1} - Detalhes: {2}..
        /// </summary>
        internal static string msgFeatureServiceConnector_Result_Error {
            get {
                return ResourceManager.GetString("msgFeatureServiceConnector_Result_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve haver ao menos um ponto na coleção..
        /// </summary>
        internal static string msgMultipoint_Error_AtLeastOnePointInTheCollection {
            get {
                return ResourceManager.GetString("msgMultipoint_Error_AtLeastOnePointInTheCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum ponto nulo é aceito na coleção..
        /// </summary>
        internal static string msgMultipoint_Error_NoNullPointAllowedInTheCollection {
            get {
                return ResourceManager.GetString("msgMultipoint_Error_NoNullPointAllowedInTheCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve haver ao menos dois pontos na coleção..
        /// </summary>
        internal static string msgPath_Error_AtLeastTwoPointsInTheCollection {
            get {
                return ResourceManager.GetString("msgPath_Error_AtLeastTwoPointsInTheCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O primeiro e o último ponto não devem ser o mesmo..
        /// </summary>
        internal static string msgPath_Error_FirstAndLastPointInTheCollectionShouldNotBeTheSame {
            get {
                return ResourceManager.GetString("msgPath_Error_FirstAndLastPointInTheCollectionShouldNotBeTheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum ponto nulo é aceito na coleção..
        /// </summary>
        internal static string msgPath_Error_NoNullPointAllowedInTheCollection {
            get {
                return ResourceManager.GetString("msgPath_Error_NoNullPointAllowedInTheCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O WKID (Well-Know ID) da &quot;Spatial Reference&quot; não pode ser igual ou menor que zero..
        /// </summary>
        internal static string msgPoint_Error_SpatialReferenceWKIDCannotBeZeroOrNegative {
            get {
                return ResourceManager.GetString("msgPoint_Error_SpatialReferenceWKIDCannotBeZeroOrNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve haver ao menos um &quot;ring&quot; na coleção..
        /// </summary>
        internal static string msgPolygon_Error_AtLeastOneRingInTheCollection {
            get {
                return ResourceManager.GetString("msgPolygon_Error_AtLeastOneRingInTheCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum &quot;ring&quot; nulo é aceito na coleção..
        /// </summary>
        internal static string msgPolygon_Error_NoNullRingAllowedInTheCollection {
            get {
                return ResourceManager.GetString("msgPolygon_Error_NoNullRingAllowedInTheCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve haver ao menos um &quot;path&quot; na coleção..
        /// </summary>
        internal static string msgPolyline_Error_AtLeastOnePathInTheCollection {
            get {
                return ResourceManager.GetString("msgPolyline_Error_AtLeastOnePathInTheCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum &quot;path&quot; nulo é aceito na coleção..
        /// </summary>
        internal static string msgPolyline_Error_NoNullPathAllowedInTheCollection {
            get {
                return ResourceManager.GetString("msgPolyline_Error_NoNullPathAllowedInTheCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve haver ao menos três pontos na coleção..
        /// </summary>
        internal static string msgRing_Error_AtLeastThreePointsInTheCollection {
            get {
                return ResourceManager.GetString("msgRing_Error_AtLeastThreePointsInTheCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O primeiro e o último ponto devem ser o mesmo..
        /// </summary>
        internal static string msgRing_Error_FirstAndLastPointInTheCollectionShouldBeTheSame {
            get {
                return ResourceManager.GetString("msgRing_Error_FirstAndLastPointInTheCollectionShouldBeTheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum ponto nulo é aceito na coleção..
        /// </summary>
        internal static string msgRing_Error_NoNullPointAllowedInTheCollection {
            get {
                return ResourceManager.GetString("msgRing_Error_NoNullPointAllowedInTheCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A coordenada do ponto não pode ser inválida..
        /// </summary>
        internal static string msgSimplePoint_Error_PointCoordinatesCannotBeInvalid {
            get {
                return ResourceManager.GetString("msgSimplePoint_Error_PointCoordinatesCannotBeInvalid", resourceCulture);
            }
        }
    }
}
